name: ci-only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Local build
        id: local_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            LDFLAGS="-s -w \
            -X github.com/inlets/inlets-operator/pkg/version.Release=${{ steps.get_tag.outputs.TAG }} \
            -X github.com/inlets/inlets-operator/pkg/version.SHA=${{ github.sha }}"
          outputs: "type=docker,push=false"
          platforms: linux/amd64
          tags: ghcr.io/inlets/inlets-operator:${{ github.sha }}
